spring:
  datasource:
   # url: jdbc:postgresql://localhost:5433/treinamento-dev?useTimezone=true&serverTimezone=UTC&useLegacyDate
    url: ${DATABASE_URL}
    #username: postgres
   # password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

server:
    port: 8080

